version: '3.6'

services:

  zipkin:
    image: openzipkin/zipkin:3
    container_name: openzipkin_server
    ports:
      - 9411:9411
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.12

  postgres_app_db:
    image: postgres:15
    container_name: postgres_banking_app
    environment:
      POSTGRES_DB: banking_core_service
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.9

  internet-banking-config-server:
    image: javatodev/internet-banking-config-server
    container_name: internet-banking-config-server
    ports:
      - 8090:8090
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.8

  internet-banking-service-registry:
    image: javatodev/internet-banking-service-registry
    container_name: internet-banking-service-registry
    ports:
      - 8081:8081
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.7

  internet-banking-api-gateway:
    image: javatodev/internet-banking-api-gateway
    container_name: internet-banking-api-gateway
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: ${SUPABASE_URL}/auth/v1/.well-known/jwks.json
    ports:
      - 8082:8082
    entrypoint: ["./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "java", "-jar", "-Dspring.profiles.active=docker", "/app.jar"]
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.6

  internet-banking-user-service:
    image: javatodev/internet-banking-user-service
    container_name: internet-banking-user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_app_db:5432/banking_core_user_service
      SPRING_DATASOURCE_USERNAME: banking_user
      SPRING_DATASOURCE_PASSWORD: banking_password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      APP_CONFIG_SUPABASE_URL: ${SUPABASE_URL}
      APP_CONFIG_SUPABASE_SERVICE-ROLE-KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - 8083:8083
    entrypoint: ["./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "postgres_app_db:5432", "--timeout=50", "--", "java", "-jar", "-Dspring.profiles.active=docker", "/app.jar"]
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.5

  internet-banking-fund-transfer-service:
    image: javatodev/internet-banking-fund-transfer-service
    container_name: internet-banking-fund-transfer-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_app_db:5432/banking_core_fund_transfer_service
      SPRING_DATASOURCE_USERNAME: banking_user
      SPRING_DATASOURCE_PASSWORD: banking_password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - 8084:8084
    entrypoint: ["./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "postgres_app_db:5432", "--timeout=50", "--", "java", "-jar", "-Dspring.profiles.active=docker", "/app.jar"]
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.4

  internet-banking-utility-payment-service:
    container_name: internet-banking-utility-payment-service
    image: javatodev/internet-banking-utility-payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_app_db:5432/banking_core_utility_payment_service
      SPRING_DATASOURCE_USERNAME: banking_user
      SPRING_DATASOURCE_PASSWORD: banking_password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - 8085:8085
    entrypoint: ["./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "postgres_app_db:5432", "--timeout=50", "--", "java", "-jar", "-Dspring.profiles.active=docker", "/app.jar"]
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.3

  core-banking-service:
    image: javatodev/core-banking-service
    container_name: core-banking-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_app_db:5432/banking_core_service
      SPRING_DATASOURCE_USERNAME: banking_user
      SPRING_DATASOURCE_PASSWORD: banking_password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - 8092:8092
    entrypoint: ["./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "postgres_app_db:5432", "--timeout=50", "--", "java", "-jar", "-Dspring.profiles.active=docker", "/app.jar"]
    networks:
      javatodev_ib_network:
        ipv4_address: 172.25.0.2

volumes:
  pgdata:

networks:
  javatodev_ib_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
