# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Building core-banking-service
      working-directory: ./core-banking-service
      run: ./gradlew build

    - name: Building internet-banking-fund-transfer-service
      working-directory: ./internet-banking-fund-transfer-service
      run: ./gradlew build

    - name: Building internet-banking-user-service
      working-directory: ./internet-banking-user-service
      run: ./gradlew build

    - name: Building internet-banking-utility-payment-service
      working-directory: ./internet-banking-utility-payment-service
      run: ./gradlew build

    - name: Building internet-banking-service-registry
      working-directory: ./internet-banking-service-registry
      run: ./gradlew build -x test

    - name: Building internet-banking-api-gateway
      working-directory: ./internet-banking-api-gateway
      run: ./gradlew build -x test
